const Iota = require('@iota/core');
const Converter = require('@iota/converter');
const iota = Iota.composeAPI({
    provider: 'https://nodes.devnet.iota.org:443' //'http://localhost:14265'
});

//console.log(Converter.asciiToTrytes("5520"))
console.log(Converter.trytesToAscii("VXZCQYNYM9N9XWTCG9AIPVLUVVXSOUCUAU9XWZRXLUFZZFLS9CQ9XCTUQXPEZFAUMKWJKYP9CHQCZYHSOGCYOUZFBPTGWBKBHLMDFXRN9ASNP9NDEGUBFWBGFB9BFWACWHJDU9SVKFKRLBEJNPUL9ECORRHYVJHLTGPA9TFRTBPBJFWJYQWUYSMCTMVYSRMYWSCMMNMRHGACBGRBVXZOUTGSOZRSZPNNYSASZZQIRSAAWNDOBYUUPSILPEDIO9Z9RPODPDIWI9FM9WDVDLEGQMNPVRJVOQTZJKYKHQRBWPVCG9PO9OVKSDIVTZUUKCAKLEXJHTCBGABIHZCPAUTZDSVHOPQYS9FLBHQDJZPZBAFDMCUPXYBMIPVUHFOJFLIWHFQQGSTL9JTYXRCWDBRBNYLSFFBKSQZSJIVIDVCSSKHWTEEHTBUTWBLNZC9JVNJKENWXCIWYOCWQGWRY9RCSHYQPUBJGFTBGWACLGXBAVOGFNS9AOWYHPZDFFDCWVRIBASB9AVF9WLTZGPSAQJYCLYBJJLEQCMGGFDUMUABW9DPFPYTLZV9CNKNVOXKLCV9HDRFPXERURMUWTBUJITND9DLRXLNJLRSCXYEWUPPCAODJWHXZJAWQUCGOSEDYQGJFJGBGFICFSUEGCCUCGEFWPVPGEEVQAATQRLARKLEAHOQVUEPFQAVWHVNQFHIDQSMCIYAODAZAYXPVMUW9YVZKMNYXRBVUHRQDGPFBYVDXSVDWMZAOQENAPDHFLXWDZKFHDUGNYIRDOEKNNOB9IFZVDUPDFYTLSW9HOCLUTNQLD9"))
// iota.getNodeInfo()
//     .then(info => console.log(info))
//     .catch(error => {
//         console.log(`Request error: ${error.message}`)

//     });   



// let tag = '5519'
// tag = Converter.asciiToTrytes(tag)
// for (var i = tag.length; i < 27; i++)
//     tag += '9';
// iota.findTransactionObjects({ tags: [tag] }).then((res) => {
//     res.forEach(element => {
//         console.log(element);
        
//     });
// })




